/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package confere_vendas;

import java.awt.Color;
import java.io.File;
import java.io.FileFilter;
import javax.swing.JFrame;

/**
 *
 * @author Antonio
 */
public class Jmain extends javax.swing.JFrame {

    /**
     * Creates new form Jmain
     */
public Jmain() {
    
    initComponents();
        
    setTitle("Confere Vendas");
    setLocation(500, 500);

    timer1.start();
    timer2.start();
    timer3.start();
   
        

    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        timer2 = new org.netbeans.examples.lib.timerbean.Timer();
        timer3 = new org.netbeans.examples.lib.timerbean.Timer();
        srn = new javax.swing.JTabbedPane();
        saoraimundo = new javax.swing.JPanel();
        srn501 = new javax.swing.JLabel();
        srn502 = new javax.swing.JLabel();
        srn503 = new javax.swing.JLabel();
        srn504 = new javax.swing.JLabel();
        srn505 = new javax.swing.JLabel();
        srn506 = new javax.swing.JLabel();
        srn507 = new javax.swing.JLabel();
        srn511 = new javax.swing.JLabel();
        srn512 = new javax.swing.JLabel();
        srn513 = new javax.swing.JLabel();
        srn514 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        piripiri301 = new javax.swing.JLabel();
        piripiri302 = new javax.swing.JLabel();
        piripiri303 = new javax.swing.JLabel();
        piripiri304 = new javax.swing.JLabel();
        piripiri305 = new javax.swing.JLabel();
        piripiri306 = new javax.swing.JLabel();
        piripiri307 = new javax.swing.JLabel();
        piripiri308 = new javax.swing.JLabel();
        piripiri309 = new javax.swing.JLabel();
        piripiri310 = new javax.swing.JLabel();
        piripiri311 = new javax.swing.JLabel();
        piripiri312 = new javax.swing.JLabel();
        piripiri313 = new javax.swing.JLabel();
        piripiri314 = new javax.swing.JLabel();
        piripiri315 = new javax.swing.JLabel();
        piripiri316 = new javax.swing.JLabel();
        piripiri317 = new javax.swing.JLabel();
        piripiri318 = new javax.swing.JLabel();
        piripiri319 = new javax.swing.JLabel();
        piripiri320 = new javax.swing.JLabel();
        piripiri321 = new javax.swing.JLabel();
        piripiri322 = new javax.swing.JLabel();
        piripiri323 = new javax.swing.JLabel();
        piripiri326 = new javax.swing.JLabel();
        piripiri327 = new javax.swing.JLabel();
        piripiri328 = new javax.swing.JLabel();
        piripiri329 = new javax.swing.JLabel();
        piripiri330 = new javax.swing.JLabel();
        piripiri331 = new javax.swing.JLabel();
        piripiri332 = new javax.swing.JLabel();
        piripiri333 = new javax.swing.JLabel();
        piripiri334 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        saoraimundo1 = new javax.swing.JPanel();
        caxias101 = new javax.swing.JLabel();
        caxias102 = new javax.swing.JLabel();
        caxias103 = new javax.swing.JLabel();
        caxias104 = new javax.swing.JLabel();
        caxias105 = new javax.swing.JLabel();
        caxias106 = new javax.swing.JLabel();
        caxias107 = new javax.swing.JLabel();
        caxias108 = new javax.swing.JLabel();
        caxias109 = new javax.swing.JLabel();
        caxias110 = new javax.swing.JLabel();
        caxias111 = new javax.swing.JLabel();
        caxias112 = new javax.swing.JLabel();
        caxias113 = new javax.swing.JLabel();
        caxias114 = new javax.swing.JLabel();
        caxias116 = new javax.swing.JLabel();
        caxias121 = new javax.swing.JLabel();
        caxias122 = new javax.swing.JLabel();
        caxias123 = new javax.swing.JLabel();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        timer2.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer2OnTime(evt);
            }
        });

        timer3.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer3OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        srn501.setForeground(new java.awt.Color(255, 51, 51));
        srn501.setText("501 - NÃO CHEGOU");

        srn502.setForeground(new java.awt.Color(255, 0, 102));
        srn502.setText("502 - NÃO CHEGOU");

        srn503.setForeground(new java.awt.Color(255, 0, 102));
        srn503.setText("503 - NÃO CHEGOU");

        srn504.setForeground(new java.awt.Color(255, 0, 102));
        srn504.setText("504 - NÃO CHEGOU");

        srn505.setForeground(new java.awt.Color(255, 0, 102));
        srn505.setText("505 - NÃO CHEGOU");

        srn506.setForeground(new java.awt.Color(255, 0, 102));
        srn506.setText("506 - NÃO CHEGOU");

        srn507.setForeground(new java.awt.Color(255, 0, 102));
        srn507.setText("507 - NÃO CHEGOU");

        srn511.setForeground(new java.awt.Color(255, 0, 102));
        srn511.setText("511 - NÃO CHEGOU");

        srn512.setForeground(new java.awt.Color(255, 0, 102));
        srn512.setText("512 - NÃO CHEGOU");

        srn513.setForeground(new java.awt.Color(255, 0, 102));
        srn513.setText("513 - NÃO CHEGOU");

        srn514.setForeground(new java.awt.Color(255, 0, 102));
        srn514.setText("513 - NÃO CHEGOU");

        javax.swing.GroupLayout saoraimundoLayout = new javax.swing.GroupLayout(saoraimundo);
        saoraimundo.setLayout(saoraimundoLayout);
        saoraimundoLayout.setHorizontalGroup(
            saoraimundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saoraimundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srn502)
                    .addComponent(srn503)
                    .addComponent(srn504)
                    .addComponent(srn505)
                    .addComponent(srn506)
                    .addComponent(srn507)
                    .addComponent(srn511)
                    .addComponent(srn512)
                    .addComponent(srn513)
                    .addComponent(srn514)
                    .addComponent(srn501))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        saoraimundoLayout.setVerticalGroup(
            saoraimundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(srn501)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn502)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn503)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn504)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn505)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn506)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn507)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn511)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn512)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn513, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn514, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        srn.addTab("São Raimundo", saoraimundo);

        piripiri301.setForeground(new java.awt.Color(255, 51, 51));
        piripiri301.setText("301 - NÃO CHEGOU");

        piripiri302.setForeground(new java.awt.Color(255, 51, 51));
        piripiri302.setText("302 - NÃO CHEGOU");

        piripiri303.setForeground(new java.awt.Color(255, 51, 51));
        piripiri303.setText("303 - NÃO CHEGOU");

        piripiri304.setForeground(new java.awt.Color(255, 51, 51));
        piripiri304.setText("304 - NÃO CHEGOU");

        piripiri305.setForeground(new java.awt.Color(255, 51, 51));
        piripiri305.setText("305 - NÃO CHEGOU");

        piripiri306.setForeground(new java.awt.Color(255, 51, 51));
        piripiri306.setText("306 - NÃO CHEGOU");

        piripiri307.setForeground(new java.awt.Color(255, 51, 51));
        piripiri307.setText("307 - NÃO CHEGOU");

        piripiri308.setForeground(new java.awt.Color(255, 51, 51));
        piripiri308.setText("308 - NÃO CHEGOU");

        piripiri309.setForeground(new java.awt.Color(255, 51, 51));
        piripiri309.setText("309 - NÃO CHEGOU");

        piripiri310.setForeground(new java.awt.Color(255, 51, 51));
        piripiri310.setText("310 - NÃO CHEGOU");

        piripiri311.setForeground(new java.awt.Color(255, 51, 51));
        piripiri311.setText("311 - NÃO CHEGOU");

        piripiri312.setForeground(new java.awt.Color(255, 51, 51));
        piripiri312.setText("312 - NÃO CHEGOU");

        piripiri313.setForeground(new java.awt.Color(255, 51, 51));
        piripiri313.setText("313 - NÃO CHEGOU");

        piripiri314.setForeground(new java.awt.Color(255, 51, 51));
        piripiri314.setText("314 - NÃO CHEGOU");

        piripiri315.setForeground(new java.awt.Color(255, 51, 51));
        piripiri315.setText("315 - NÃO CHEGOU");

        piripiri316.setForeground(new java.awt.Color(255, 51, 51));
        piripiri316.setText("316 - NÃO CHEGOU");

        piripiri317.setForeground(new java.awt.Color(255, 51, 51));
        piripiri317.setText("317 - NÃO CHEGOU");

        piripiri318.setForeground(new java.awt.Color(255, 51, 51));
        piripiri318.setText("318 - NÃO CHEGOU");

        piripiri319.setForeground(new java.awt.Color(255, 51, 51));
        piripiri319.setText("319 - NÃO CHEGOU");

        piripiri320.setForeground(new java.awt.Color(255, 51, 51));
        piripiri320.setText("320 - NÃO CHEGOU");

        piripiri321.setForeground(new java.awt.Color(255, 51, 51));
        piripiri321.setText("321 - NÃO CHEGOU");

        piripiri322.setForeground(new java.awt.Color(255, 51, 51));
        piripiri322.setText("322 - NÃO CHEGOU");

        piripiri323.setForeground(new java.awt.Color(255, 51, 51));
        piripiri323.setText("323 - NÃO CHEGOU");

        piripiri326.setForeground(new java.awt.Color(255, 51, 51));
        piripiri326.setText("326 - NÃO CHEGOU");

        piripiri327.setForeground(new java.awt.Color(255, 51, 51));
        piripiri327.setText("327 - NÃO CHEGOU");

        piripiri328.setForeground(new java.awt.Color(255, 51, 51));
        piripiri328.setText("328 - NÃO CHEGOU");

        piripiri329.setForeground(new java.awt.Color(255, 51, 51));
        piripiri329.setText("329 - NÃO CHEGOU");

        piripiri330.setForeground(new java.awt.Color(255, 51, 51));
        piripiri330.setText("330 - NÃO CHEGOU");

        piripiri331.setForeground(new java.awt.Color(255, 51, 51));
        piripiri331.setText("331 - NÃO CHEGOU");

        piripiri332.setForeground(new java.awt.Color(255, 51, 51));
        piripiri332.setText("332 - NÃO CHEGOU");

        piripiri333.setForeground(new java.awt.Color(255, 51, 51));
        piripiri333.setText("333 - NÃO CHEGOU");

        piripiri334.setForeground(new java.awt.Color(255, 51, 51));
        piripiri334.setText("334 - NÃO CHEGOU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piripiri309)
                    .addComponent(piripiri310)
                    .addComponent(piripiri311)
                    .addComponent(piripiri312)
                    .addComponent(piripiri313)
                    .addComponent(piripiri308)
                    .addComponent(piripiri302)
                    .addComponent(piripiri303)
                    .addComponent(piripiri304)
                    .addComponent(piripiri305)
                    .addComponent(piripiri306)
                    .addComponent(piripiri307)
                    .addComponent(piripiri301))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piripiri314)
                    .addComponent(piripiri320)
                    .addComponent(piripiri321)
                    .addComponent(piripiri322)
                    .addComponent(piripiri323)
                    .addComponent(piripiri326)
                    .addComponent(piripiri327)
                    .addComponent(piripiri328)
                    .addComponent(piripiri315)
                    .addComponent(piripiri316)
                    .addComponent(piripiri317)
                    .addComponent(piripiri318)
                    .addComponent(piripiri319))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piripiri329)
                    .addComponent(piripiri330)
                    .addComponent(piripiri331)
                    .addComponent(piripiri332)
                    .addComponent(piripiri333)
                    .addComponent(piripiri334))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(piripiri301)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri302)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri303)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri304)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri305)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri306)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri307)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri308)
                            .addComponent(piripiri321))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri309)
                            .addComponent(piripiri322))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri310)
                            .addComponent(piripiri323))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri311)
                            .addComponent(piripiri326))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri312)
                            .addComponent(piripiri327))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri313)
                            .addComponent(piripiri328)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri314)
                            .addComponent(piripiri329))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri315)
                            .addComponent(piripiri330))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri316)
                            .addComponent(piripiri331))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri317)
                            .addComponent(piripiri332))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri318)
                            .addComponent(piripiri333))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri319)
                            .addComponent(piripiri334))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri320)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        srn.addTab("Piripiri", jPanel1);

        caxias101.setForeground(new java.awt.Color(255, 51, 51));
        caxias101.setText("101 - NÃO CHEGOU");

        caxias102.setForeground(new java.awt.Color(255, 0, 102));
        caxias102.setText("102 - NÃO CHEGOU");

        caxias103.setForeground(new java.awt.Color(255, 0, 102));
        caxias103.setText("103 - NÃO CHEGOU");

        caxias104.setForeground(new java.awt.Color(255, 0, 102));
        caxias104.setText("104 - NÃO CHEGOU");

        caxias105.setForeground(new java.awt.Color(255, 0, 102));
        caxias105.setText("105 - NÃO CHEGOU");

        caxias106.setForeground(new java.awt.Color(255, 0, 102));
        caxias106.setText("106 - NÃO CHEGOU");

        caxias107.setForeground(new java.awt.Color(255, 0, 102));
        caxias107.setText("107 - NÃO CHEGOU");

        caxias108.setForeground(new java.awt.Color(255, 0, 102));
        caxias108.setText("108 - NÃO CHEGOU");

        caxias109.setForeground(new java.awt.Color(255, 0, 102));
        caxias109.setText("109 - NÃO CHEGOU");

        caxias110.setForeground(new java.awt.Color(255, 0, 102));
        caxias110.setText("110 - NÃO CHEGOU");

        caxias111.setForeground(new java.awt.Color(255, 0, 102));
        caxias111.setText("111 - NÃO CHEGOU");

        caxias112.setForeground(new java.awt.Color(255, 0, 102));
        caxias112.setText("112 - NÃO CHEGOU");

        caxias113.setForeground(new java.awt.Color(255, 0, 102));
        caxias113.setText("113 - NÃO CHEGOU");

        caxias114.setForeground(new java.awt.Color(255, 0, 102));
        caxias114.setText("114 - NÃO CHEGOU");

        caxias116.setForeground(new java.awt.Color(255, 0, 102));
        caxias116.setText("116 - NÃO CHEGOU");

        caxias121.setForeground(new java.awt.Color(255, 0, 102));
        caxias121.setText("121 - NÃO CHEGOU");

        caxias122.setForeground(new java.awt.Color(255, 0, 102));
        caxias122.setText("122 - NÃO CHEGOU");

        caxias123.setForeground(new java.awt.Color(255, 0, 102));
        caxias123.setText("123 - NÃO CHEGOU");

        javax.swing.GroupLayout saoraimundo1Layout = new javax.swing.GroupLayout(saoraimundo1);
        saoraimundo1.setLayout(saoraimundo1Layout);
        saoraimundo1Layout.setHorizontalGroup(
            saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias101)
                        .addGap(18, 18, 18)
                        .addComponent(caxias114))
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias103)
                        .addGap(18, 18, 18)
                        .addComponent(caxias121))
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias104)
                        .addGap(18, 18, 18)
                        .addComponent(caxias122))
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias105)
                        .addGap(18, 18, 18)
                        .addComponent(caxias123))
                    .addComponent(caxias106)
                    .addComponent(caxias107)
                    .addComponent(caxias108)
                    .addComponent(caxias109)
                    .addComponent(caxias110)
                    .addComponent(caxias111)
                    .addComponent(caxias112)
                    .addComponent(caxias113)
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias102)
                        .addGap(18, 18, 18)
                        .addComponent(caxias116)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        saoraimundo1Layout.setVerticalGroup(
            saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias101)
                    .addComponent(caxias114, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias102)
                    .addComponent(caxias116, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias103)
                    .addComponent(caxias121, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias104)
                    .addComponent(caxias122, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias105)
                    .addComponent(caxias123, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias107)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias108)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias109)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias110, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias111, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias112, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias113, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saoraimundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saoraimundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        srn.addTab("Caxias", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srn)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srn)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        File diretorio = new File("C:\\Users\\anton\\Documents\\SRN");
        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
                if (pathname.getName().endsWith("301.TXT.GZ") == true) {
                    piripiri301.setText("301 Chegou");
                    piripiri301.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("302.TXT.GZ") == true) {
                    piripiri302.setText("302 Chegou");
                    piripiri302.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("303.TXT.GZ") == true) {
                    piripiri303.setText("303 Chegou");
                    piripiri303.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("304.TXT.GZ") == true) {
                    piripiri304.setText("304 Chegou");
                    piripiri304.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("305.TXT.GZ") == true) {
                    piripiri305.setText("305 Chegou");
                    piripiri305.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("306.TXT.GZ") == true) {
                    piripiri306.setText("306 Chegou");
                    piripiri306.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("307.TXT.GZ") == true) {
                    piripiri307.setText("307 Chegou");
                    piripiri307.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("308.TXT.GZ") == true) {
                    piripiri308.setText("308 Chegou");
                    piripiri308.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("309.TXT.GZ") == true) {
                    piripiri309.setText("309 Chegou");
                    piripiri309.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("310.TXT.GZ") == true) {
                    piripiri310.setText("310 Chegou");
                    piripiri310.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("311.TXT.GZ") == true) {
                    piripiri310.setText("311 Chegou");
                    piripiri310.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("312.TXT.GZ") == true) {
                    piripiri312.setText("312 Chegou");
                    piripiri312.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("313.TXT.GZ") == true) {
                    piripiri313.setText("313 Chegou");
                    piripiri313.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("314.TXT.GZ") == true) {
                    piripiri314.setText("314 Chegou");
                    piripiri314.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("315.TXT.GZ") == true) {
                    piripiri315.setText("315 Chegou");
                    piripiri315.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("316.TXT.GZ") == true) {
                    piripiri316.setText("316 Chegou");
                    piripiri316.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("317.TXT.GZ") == true) {
                    piripiri317.setText("317 Chegou");
                    piripiri317.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("318.TXT.GZ") == true) {
                    piripiri318.setText("318 Chegou");
                    piripiri318.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("319.TXT.GZ") == true) {
                    piripiri319.setText("319 Chegou");
                    piripiri319.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("320.TXT.GZ") == true) {
                    piripiri320.setText("320 Chegou");
                    piripiri320.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("321.TXT.GZ") == true) {
                    piripiri321.setText("321 Chegou");
                    piripiri321.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("322.TXT.GZ") == true) {
                    piripiri322.setText("322 Chegou");
                    piripiri322.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("323.TXT.GZ") == true) {
                    piripiri323.setText("323 Chegou");
                    piripiri323.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("326.TXT.GZ") == true) {
                    piripiri326.setText("326 Chegou");
                    piripiri326.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("327.TXT.GZ") == true) {
                    piripiri327.setText("327 Chegou");
                    piripiri327.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("328.TXT.GZ") == true) {
                    piripiri328.setText("328 Chegou");
                    piripiri328.setForeground(Color.blue);
                }              
                if (pathname.getName().endsWith("329.TXT.GZ") == true) {
                    piripiri329.setText("329 Chegou");
                    piripiri329.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("330.TXT.GZ") == true) {
                    piripiri330.setText("330 Chegou");
                    piripiri330.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("331.TXT.GZ") == true) {
                    piripiri331.setText("331 Chegou");
                    piripiri331.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("332.TXT.GZ") == true) {
                    piripiri332.setText("332 Chegou");
                    piripiri332.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("333.TXT.GZ") == true) {
                    piripiri333.setText("333 Chegou");
                    piripiri333.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("334.TXT.GZ") == true) {
                    piripiri334.setText("334 Chegou");
                    piripiri334.setForeground(Color.blue);
                }                
        return true;
        }      
        });
    }//GEN-LAST:event_timer1OnTime

    private void timer2OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer2OnTime
        File diretorio = new File("C:\\Users\\anton\\Documents\\SRN");
	
    
        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
                if (pathname.getName().endsWith("501.TXT.GZ") == true) {
                    srn501.setText("501 Chegou");
                    srn501.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("502.TXT.GZ") == true) {
                    srn502.setText("502 Chegou");
                    srn502.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("503.TXT.GZ") == true) {
                    srn503.setText("503 Chegou");
                    srn503.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("504.TXT.GZ") == true) {
                    srn504.setText("504 Chegou");
                    srn504.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("505.TXT.GZ") == true) {
                    srn505.setText("505 Chegou");
                    srn505.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("506.TXT.GZ") == true) {
                    srn506.setText("506 Chegou");
                    srn506.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("507.TXT.GZ") == true) {
                    srn507.setText("507 Chegou");
                    srn507.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("511.TXT.GZ") == true) {
                    srn511.setText("511 Chegou");
                    srn511.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("512.TXT.GZ") == true) {
                    srn512.setText("512 Chegou");
                    srn512.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("513.TXT.GZ") == true) {
                    srn513.setText("513 Chegou");
                    srn513.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("514.TXT.GZ") == true) {
                    srn514.setText("514 Chegou");
                    srn514.setForeground(Color.blue);
                }
        return true;
        }      
        });
    }//GEN-LAST:event_timer2OnTime

    private void timer3OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer3OnTime
        File diretorio = new File("C:\\Users\\anton\\Documents\\SRN");
	
        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
            if (pathname.getName().endsWith("101.TXT.GZ") == true) {
                caxias101.setText("101 Chegou");
                caxias101.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("102.TXT.GZ") == true) {
                caxias102.setText("102 Chegou");
                caxias102.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("101.TXT.GZ") == true) {
                caxias103.setText("101 Chegou");
                caxias103.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("104.TXT.GZ") == true) {
                caxias104.setText("104 Chegou");
                caxias104.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("105.TXT.GZ") == true) {
                caxias105.setText("105 Chegou");
                caxias105.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("106.TXT.GZ") == true) {
                caxias106.setText("106 Chegou");
                caxias106.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("107.TXT.GZ") == true) {
                caxias107.setText("107 Chegou");
                caxias107.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("108.TXT.GZ") == true) {
                caxias108.setText("108 Chegou");
                caxias108.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("109.TXT.GZ") == true) {
                caxias109.setText("109 Chegou");
                caxias109.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("110.TXT.GZ") == true) {
                caxias110.setText("110 Chegou");
                caxias110.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("111.TXT.GZ") == true) {
                caxias111.setText("111 Chegou");
                caxias111.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("112.TXT.GZ") == true) {
                caxias112.setText("112 Chegou");
                caxias112.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("113.TXT.GZ") == true) {
                caxias113.setText("113 Chegou");
                caxias113.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("114.TXT.GZ") == true) {
                caxias114.setText("114 Chegou");
                caxias114.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("116.TXT.GZ") == true) {
                caxias116.setText("116 Chegou");
                caxias116.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("121.TXT.GZ") == true) {
                caxias121.setText("121 Chegou");
                caxias121.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("122.TXT.GZ") == true) {
                caxias122.setText("122 Chegou");
                caxias122.setForeground(Color.blue);
                }
             if (pathname.getName().endsWith("123.TXT.GZ") == true) {
                caxias123.setText("123 Chegou");
                caxias123.setForeground(Color.blue);
                }

               return true;
        }      
        });
    }//GEN-LAST:event_timer3OnTime

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caxias101;
    private javax.swing.JLabel caxias102;
    private javax.swing.JLabel caxias103;
    private javax.swing.JLabel caxias104;
    private javax.swing.JLabel caxias105;
    private javax.swing.JLabel caxias106;
    private javax.swing.JLabel caxias107;
    private javax.swing.JLabel caxias108;
    private javax.swing.JLabel caxias109;
    private javax.swing.JLabel caxias110;
    private javax.swing.JLabel caxias111;
    private javax.swing.JLabel caxias112;
    private javax.swing.JLabel caxias113;
    private javax.swing.JLabel caxias114;
    private javax.swing.JLabel caxias116;
    private javax.swing.JLabel caxias121;
    private javax.swing.JLabel caxias122;
    private javax.swing.JLabel caxias123;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel piripiri301;
    private javax.swing.JLabel piripiri302;
    private javax.swing.JLabel piripiri303;
    private javax.swing.JLabel piripiri304;
    private javax.swing.JLabel piripiri305;
    private javax.swing.JLabel piripiri306;
    private javax.swing.JLabel piripiri307;
    private javax.swing.JLabel piripiri308;
    private javax.swing.JLabel piripiri309;
    private javax.swing.JLabel piripiri310;
    private javax.swing.JLabel piripiri311;
    private javax.swing.JLabel piripiri312;
    private javax.swing.JLabel piripiri313;
    private javax.swing.JLabel piripiri314;
    private javax.swing.JLabel piripiri315;
    private javax.swing.JLabel piripiri316;
    private javax.swing.JLabel piripiri317;
    private javax.swing.JLabel piripiri318;
    private javax.swing.JLabel piripiri319;
    private javax.swing.JLabel piripiri320;
    private javax.swing.JLabel piripiri321;
    private javax.swing.JLabel piripiri322;
    private javax.swing.JLabel piripiri323;
    private javax.swing.JLabel piripiri326;
    private javax.swing.JLabel piripiri327;
    private javax.swing.JLabel piripiri328;
    private javax.swing.JLabel piripiri329;
    private javax.swing.JLabel piripiri330;
    private javax.swing.JLabel piripiri331;
    private javax.swing.JLabel piripiri332;
    private javax.swing.JLabel piripiri333;
    private javax.swing.JLabel piripiri334;
    private javax.swing.JPanel saoraimundo;
    private javax.swing.JPanel saoraimundo1;
    private javax.swing.JTabbedPane srn;
    private javax.swing.JLabel srn501;
    private javax.swing.JLabel srn502;
    private javax.swing.JLabel srn503;
    private javax.swing.JLabel srn504;
    private javax.swing.JLabel srn505;
    private javax.swing.JLabel srn506;
    private javax.swing.JLabel srn507;
    private javax.swing.JLabel srn511;
    private javax.swing.JLabel srn512;
    private javax.swing.JLabel srn513;
    private javax.swing.JLabel srn514;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private org.netbeans.examples.lib.timerbean.Timer timer2;
    private org.netbeans.examples.lib.timerbean.Timer timer3;
    // End of variables declaration//GEN-END:variables
}
