/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package confere_vendas;

import java.awt.Color;
import java.io.File;
import java.io.FileFilter;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class Jmain extends javax.swing.JFrame {

    /**
     * Creates new form Jmain
     */
public Jmain() {
    
    initComponents();
    
    
    setTitle("Confere Vendas");
    this.setLocationRelativeTo(null);
    setResizable(false);

    

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piripiri = new org.netbeans.examples.lib.timerbean.Timer();
        picos = new org.netbeans.examples.lib.timerbean.Timer();
        caxias = new org.netbeans.examples.lib.timerbean.Timer();
        sraimundo = new org.netbeans.examples.lib.timerbean.Timer();
        floriano = new org.netbeans.examples.lib.timerbean.Timer();
        srn = new javax.swing.JTabbedPane();
        saoraimundo = new javax.swing.JPanel();
        srn501 = new javax.swing.JLabel();
        srn502 = new javax.swing.JLabel();
        srn503 = new javax.swing.JLabel();
        srn504 = new javax.swing.JLabel();
        srn505 = new javax.swing.JLabel();
        srn506 = new javax.swing.JLabel();
        srn507 = new javax.swing.JLabel();
        srn511 = new javax.swing.JLabel();
        srn512 = new javax.swing.JLabel();
        srn513 = new javax.swing.JLabel();
        srn514 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        piripiri301 = new javax.swing.JLabel();
        piripiri302 = new javax.swing.JLabel();
        piripiri303 = new javax.swing.JLabel();
        piripiri304 = new javax.swing.JLabel();
        piripiri305 = new javax.swing.JLabel();
        piripiri306 = new javax.swing.JLabel();
        piripiri307 = new javax.swing.JLabel();
        piripiri308 = new javax.swing.JLabel();
        piripiri309 = new javax.swing.JLabel();
        piripiri310 = new javax.swing.JLabel();
        piripiri311 = new javax.swing.JLabel();
        piripiri312 = new javax.swing.JLabel();
        piripiri313 = new javax.swing.JLabel();
        piripiri314 = new javax.swing.JLabel();
        piripiri315 = new javax.swing.JLabel();
        piripiri316 = new javax.swing.JLabel();
        piripiri317 = new javax.swing.JLabel();
        piripiri318 = new javax.swing.JLabel();
        piripiri319 = new javax.swing.JLabel();
        piripiri320 = new javax.swing.JLabel();
        piripiri321 = new javax.swing.JLabel();
        piripiri322 = new javax.swing.JLabel();
        piripiri323 = new javax.swing.JLabel();
        piripiri326 = new javax.swing.JLabel();
        piripiri327 = new javax.swing.JLabel();
        piripiri328 = new javax.swing.JLabel();
        piripiri329 = new javax.swing.JLabel();
        piripiri330 = new javax.swing.JLabel();
        piripiri331 = new javax.swing.JLabel();
        piripiri332 = new javax.swing.JLabel();
        piripiri333 = new javax.swing.JLabel();
        piripiri334 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        saoraimundo1 = new javax.swing.JPanel();
        caxias101 = new javax.swing.JLabel();
        caxias102 = new javax.swing.JLabel();
        caxias103 = new javax.swing.JLabel();
        caxias104 = new javax.swing.JLabel();
        caxias105 = new javax.swing.JLabel();
        caxias106 = new javax.swing.JLabel();
        caxias107 = new javax.swing.JLabel();
        caxias108 = new javax.swing.JLabel();
        caxias109 = new javax.swing.JLabel();
        caxias110 = new javax.swing.JLabel();
        caxias111 = new javax.swing.JLabel();
        caxias112 = new javax.swing.JLabel();
        caxias113 = new javax.swing.JLabel();
        caxias114 = new javax.swing.JLabel();
        caxias116 = new javax.swing.JLabel();
        caxias121 = new javax.swing.JLabel();
        caxias122 = new javax.swing.JLabel();
        caxias123 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        picos201 = new javax.swing.JLabel();
        picos202 = new javax.swing.JLabel();
        picos203 = new javax.swing.JLabel();
        picos204 = new javax.swing.JLabel();
        picos205 = new javax.swing.JLabel();
        picos206 = new javax.swing.JLabel();
        picos207 = new javax.swing.JLabel();
        picos208 = new javax.swing.JLabel();
        picos209 = new javax.swing.JLabel();
        picos210 = new javax.swing.JLabel();
        picos211 = new javax.swing.JLabel();
        picos212 = new javax.swing.JLabel();
        picos213 = new javax.swing.JLabel();
        picos214 = new javax.swing.JLabel();
        picos215 = new javax.swing.JLabel();
        picos216 = new javax.swing.JLabel();
        picos217 = new javax.swing.JLabel();
        picos218 = new javax.swing.JLabel();
        picos219 = new javax.swing.JLabel();
        picos220 = new javax.swing.JLabel();
        picos221 = new javax.swing.JLabel();
        picos222 = new javax.swing.JLabel();
        picos223 = new javax.swing.JLabel();
        picos226 = new javax.swing.JLabel();
        picos227 = new javax.swing.JLabel();
        picos228 = new javax.swing.JLabel();
        picos229 = new javax.swing.JLabel();
        picos230 = new javax.swing.JLabel();
        picos231 = new javax.swing.JLabel();
        picos232 = new javax.swing.JLabel();
        picos234 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        floriano401 = new javax.swing.JLabel();
        floriano402 = new javax.swing.JLabel();
        floriano403 = new javax.swing.JLabel();
        floriano404 = new javax.swing.JLabel();
        floriano405 = new javax.swing.JLabel();
        floriano406 = new javax.swing.JLabel();
        floriano407 = new javax.swing.JLabel();
        floriano408 = new javax.swing.JLabel();
        floriano409 = new javax.swing.JLabel();
        floriano410 = new javax.swing.JLabel();
        floriano411 = new javax.swing.JLabel();
        floriano412 = new javax.swing.JLabel();
        floriano413 = new javax.swing.JLabel();
        floriano414 = new javax.swing.JLabel();
        floriano415 = new javax.swing.JLabel();
        floriano416 = new javax.swing.JLabel();
        floriano417 = new javax.swing.JLabel();
        floriano419 = new javax.swing.JLabel();
        floriano426 = new javax.swing.JLabel();
        floriano427 = new javax.swing.JLabel();
        floriano428 = new javax.swing.JLabel();
        floriano429 = new javax.swing.JLabel();
        floriano430 = new javax.swing.JLabel();
        floriano431 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ativarPicos = new javax.swing.JCheckBox();
        ativarPiripiri = new javax.swing.JCheckBox();
        ativarFloriano = new javax.swing.JCheckBox();
        ativarSrn = new javax.swing.JCheckBox();
        ativarCaxias = new javax.swing.JCheckBox();

        piripiri.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                piripiriOnTime(evt);
            }
        });

        picos.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                picosOnTime(evt);
            }
        });

        caxias.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                caxiasOnTime(evt);
            }
        });

        sraimundo.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                sraimundoOnTime(evt);
            }
        });

        floriano.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                florianoOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        srn501.setForeground(new java.awt.Color(255, 51, 51));
        srn501.setText("501 - NÃO CHEGOU");

        srn502.setForeground(new java.awt.Color(255, 51, 51));
        srn502.setText("502 - NÃO CHEGOU");

        srn503.setForeground(new java.awt.Color(255, 51, 51));
        srn503.setText("503 - NÃO CHEGOU");

        srn504.setForeground(new java.awt.Color(255, 51, 51));
        srn504.setText("504 - NÃO CHEGOU");

        srn505.setForeground(new java.awt.Color(255, 51, 51));
        srn505.setText("505 - NÃO CHEGOU");

        srn506.setForeground(new java.awt.Color(255, 51, 51));
        srn506.setText("506 - NÃO CHEGOU");

        srn507.setForeground(new java.awt.Color(255, 51, 51));
        srn507.setText("507 - NÃO CHEGOU");

        srn511.setForeground(new java.awt.Color(255, 51, 51));
        srn511.setText("511 - NÃO CHEGOU");

        srn512.setForeground(new java.awt.Color(255, 51, 51));
        srn512.setText("512 - NÃO CHEGOU");

        srn513.setForeground(new java.awt.Color(255, 51, 51));
        srn513.setText("513 - NÃO CHEGOU");

        srn514.setForeground(new java.awt.Color(255, 51, 51));
        srn514.setText("514 - NÃO CHEGOU");

        javax.swing.GroupLayout saoraimundoLayout = new javax.swing.GroupLayout(saoraimundo);
        saoraimundo.setLayout(saoraimundoLayout);
        saoraimundoLayout.setHorizontalGroup(
            saoraimundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saoraimundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srn502)
                    .addComponent(srn503)
                    .addComponent(srn504)
                    .addComponent(srn505)
                    .addComponent(srn506)
                    .addComponent(srn507)
                    .addComponent(srn511)
                    .addComponent(srn512)
                    .addComponent(srn513)
                    .addComponent(srn514)
                    .addComponent(srn501))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        saoraimundoLayout.setVerticalGroup(
            saoraimundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(srn501)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn502)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn503)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn504)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn505)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn506)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn507)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn511)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn512)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn513, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srn514, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        srn.addTab("São Raimundo", saoraimundo);

        piripiri301.setForeground(new java.awt.Color(255, 51, 51));
        piripiri301.setText("301 - NÃO CHEGOU");

        piripiri302.setForeground(new java.awt.Color(255, 51, 51));
        piripiri302.setText("302 - NÃO CHEGOU");

        piripiri303.setForeground(new java.awt.Color(255, 51, 51));
        piripiri303.setText("303 - NÃO CHEGOU");

        piripiri304.setForeground(new java.awt.Color(255, 51, 51));
        piripiri304.setText("304 - NÃO CHEGOU");

        piripiri305.setForeground(new java.awt.Color(255, 51, 51));
        piripiri305.setText("305 - NÃO CHEGOU");

        piripiri306.setForeground(new java.awt.Color(255, 51, 51));
        piripiri306.setText("306 - NÃO CHEGOU");

        piripiri307.setForeground(new java.awt.Color(255, 51, 51));
        piripiri307.setText("307 - NÃO CHEGOU");

        piripiri308.setForeground(new java.awt.Color(255, 51, 51));
        piripiri308.setText("308 - NÃO CHEGOU");

        piripiri309.setForeground(new java.awt.Color(255, 51, 51));
        piripiri309.setText("309 - NÃO CHEGOU");

        piripiri310.setForeground(new java.awt.Color(255, 51, 51));
        piripiri310.setText("310 - NÃO CHEGOU");

        piripiri311.setForeground(new java.awt.Color(255, 51, 51));
        piripiri311.setText("311 - NÃO CHEGOU");

        piripiri312.setForeground(new java.awt.Color(255, 51, 51));
        piripiri312.setText("312 - NÃO CHEGOU");

        piripiri313.setForeground(new java.awt.Color(255, 51, 51));
        piripiri313.setText("313 - NÃO CHEGOU");

        piripiri314.setForeground(new java.awt.Color(255, 51, 51));
        piripiri314.setText("314 - NÃO CHEGOU");

        piripiri315.setForeground(new java.awt.Color(255, 51, 51));
        piripiri315.setText("315 - NÃO CHEGOU");

        piripiri316.setForeground(new java.awt.Color(255, 51, 51));
        piripiri316.setText("316 - NÃO CHEGOU");

        piripiri317.setForeground(new java.awt.Color(255, 51, 51));
        piripiri317.setText("317 - NÃO CHEGOU");

        piripiri318.setForeground(new java.awt.Color(255, 51, 51));
        piripiri318.setText("318 - NÃO CHEGOU");

        piripiri319.setForeground(new java.awt.Color(255, 51, 51));
        piripiri319.setText("319 - NÃO CHEGOU");

        piripiri320.setForeground(new java.awt.Color(255, 51, 51));
        piripiri320.setText("320 - NÃO CHEGOU");

        piripiri321.setForeground(new java.awt.Color(255, 51, 51));
        piripiri321.setText("321 - NÃO CHEGOU");

        piripiri322.setForeground(new java.awt.Color(255, 51, 51));
        piripiri322.setText("322 - NÃO CHEGOU");

        piripiri323.setForeground(new java.awt.Color(255, 51, 51));
        piripiri323.setText("323 - NÃO CHEGOU");

        piripiri326.setForeground(new java.awt.Color(255, 51, 51));
        piripiri326.setText("326 - NÃO CHEGOU");

        piripiri327.setForeground(new java.awt.Color(255, 51, 51));
        piripiri327.setText("327 - NÃO CHEGOU");

        piripiri328.setForeground(new java.awt.Color(255, 51, 51));
        piripiri328.setText("328 - NÃO CHEGOU");

        piripiri329.setForeground(new java.awt.Color(255, 51, 51));
        piripiri329.setText("329 - NÃO CHEGOU");

        piripiri330.setForeground(new java.awt.Color(255, 51, 51));
        piripiri330.setText("330 - NÃO CHEGOU");

        piripiri331.setForeground(new java.awt.Color(255, 51, 51));
        piripiri331.setText("331 - NÃO CHEGOU");

        piripiri332.setForeground(new java.awt.Color(255, 51, 51));
        piripiri332.setText("332 - NÃO CHEGOU");

        piripiri333.setForeground(new java.awt.Color(255, 51, 51));
        piripiri333.setText("333 - NÃO CHEGOU");

        piripiri334.setForeground(new java.awt.Color(255, 51, 51));
        piripiri334.setText("334 - NÃO CHEGOU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piripiri309)
                    .addComponent(piripiri310)
                    .addComponent(piripiri311)
                    .addComponent(piripiri312)
                    .addComponent(piripiri313)
                    .addComponent(piripiri308)
                    .addComponent(piripiri302)
                    .addComponent(piripiri303)
                    .addComponent(piripiri304)
                    .addComponent(piripiri305)
                    .addComponent(piripiri306)
                    .addComponent(piripiri307)
                    .addComponent(piripiri301))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piripiri314)
                    .addComponent(piripiri320)
                    .addComponent(piripiri321)
                    .addComponent(piripiri322)
                    .addComponent(piripiri323)
                    .addComponent(piripiri326)
                    .addComponent(piripiri327)
                    .addComponent(piripiri328)
                    .addComponent(piripiri315)
                    .addComponent(piripiri316)
                    .addComponent(piripiri317)
                    .addComponent(piripiri318)
                    .addComponent(piripiri319))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piripiri329)
                    .addComponent(piripiri330)
                    .addComponent(piripiri331)
                    .addComponent(piripiri332)
                    .addComponent(piripiri333)
                    .addComponent(piripiri334))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(piripiri301)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri302)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri303)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri304)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri305)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri306)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri307)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri308)
                            .addComponent(piripiri321))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri309)
                            .addComponent(piripiri322))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri310)
                            .addComponent(piripiri323))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri311)
                            .addComponent(piripiri326))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri312)
                            .addComponent(piripiri327))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri313)
                            .addComponent(piripiri328)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri314)
                            .addComponent(piripiri329))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri315)
                            .addComponent(piripiri330))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri316)
                            .addComponent(piripiri331))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri317)
                            .addComponent(piripiri332))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri318)
                            .addComponent(piripiri333))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(piripiri319)
                            .addComponent(piripiri334))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piripiri320)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        srn.addTab("Piripiri", jPanel1);

        caxias101.setForeground(new java.awt.Color(255, 51, 51));
        caxias101.setText("101 - NÃO CHEGOU");

        caxias102.setForeground(new java.awt.Color(255, 51, 51));
        caxias102.setText("102 - NÃO CHEGOU");

        caxias103.setForeground(new java.awt.Color(255, 51, 51));
        caxias103.setText("103 - NÃO CHEGOU");

        caxias104.setForeground(new java.awt.Color(255, 51, 51));
        caxias104.setText("104 - NÃO CHEGOU");

        caxias105.setForeground(new java.awt.Color(255, 51, 51));
        caxias105.setText("105 - NÃO CHEGOU");

        caxias106.setForeground(new java.awt.Color(255, 51, 51));
        caxias106.setText("106 - NÃO CHEGOU");

        caxias107.setForeground(new java.awt.Color(255, 51, 51));
        caxias107.setText("107 - NÃO CHEGOU");

        caxias108.setForeground(new java.awt.Color(255, 51, 51));
        caxias108.setText("108 - NÃO CHEGOU");

        caxias109.setForeground(new java.awt.Color(255, 51, 51));
        caxias109.setText("109 - NÃO CHEGOU");

        caxias110.setForeground(new java.awt.Color(255, 51, 51));
        caxias110.setText("110 - NÃO CHEGOU");

        caxias111.setForeground(new java.awt.Color(255, 51, 51));
        caxias111.setText("111 - NÃO CHEGOU");

        caxias112.setForeground(new java.awt.Color(255, 51, 51));
        caxias112.setText("112 - NÃO CHEGOU");

        caxias113.setForeground(new java.awt.Color(255, 51, 51));
        caxias113.setText("113 - NÃO CHEGOU");

        caxias114.setForeground(new java.awt.Color(255, 51, 51));
        caxias114.setText("114 - NÃO CHEGOU");

        caxias116.setForeground(new java.awt.Color(255, 51, 51));
        caxias116.setText("116 - NÃO CHEGOU");

        caxias121.setForeground(new java.awt.Color(255, 51, 51));
        caxias121.setText("121 - NÃO CHEGOU");

        caxias122.setForeground(new java.awt.Color(255, 51, 51));
        caxias122.setText("122 - NÃO CHEGOU");

        caxias123.setForeground(new java.awt.Color(255, 51, 51));
        caxias123.setText("123 - NÃO CHEGOU");

        javax.swing.GroupLayout saoraimundo1Layout = new javax.swing.GroupLayout(saoraimundo1);
        saoraimundo1.setLayout(saoraimundo1Layout);
        saoraimundo1Layout.setHorizontalGroup(
            saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias101)
                        .addGap(18, 18, 18)
                        .addComponent(caxias114))
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias103)
                        .addGap(18, 18, 18)
                        .addComponent(caxias121))
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias104)
                        .addGap(18, 18, 18)
                        .addComponent(caxias122))
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias105)
                        .addGap(18, 18, 18)
                        .addComponent(caxias123))
                    .addComponent(caxias106)
                    .addComponent(caxias107)
                    .addComponent(caxias108)
                    .addComponent(caxias109)
                    .addComponent(caxias110)
                    .addComponent(caxias111)
                    .addComponent(caxias112)
                    .addComponent(caxias113)
                    .addGroup(saoraimundo1Layout.createSequentialGroup()
                        .addComponent(caxias102)
                        .addGap(18, 18, 18)
                        .addComponent(caxias116)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        saoraimundo1Layout.setVerticalGroup(
            saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saoraimundo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias101)
                    .addComponent(caxias114, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias102)
                    .addComponent(caxias116, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias103)
                    .addComponent(caxias121, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias104)
                    .addComponent(caxias122, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saoraimundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caxias105)
                    .addComponent(caxias123, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias107)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias108)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias109)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias110, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias111, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias112, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caxias113, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saoraimundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saoraimundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        srn.addTab("Caxias", jPanel2);

        picos201.setForeground(new java.awt.Color(255, 51, 51));
        picos201.setText("201 - NÃO CHEGOU");

        picos202.setForeground(new java.awt.Color(255, 51, 51));
        picos202.setText("202 - NÃO CHEGOU");

        picos203.setForeground(new java.awt.Color(255, 51, 51));
        picos203.setText("203 - NÃO CHEGOU");

        picos204.setForeground(new java.awt.Color(255, 51, 51));
        picos204.setText("204 - NÃO CHEGOU");

        picos205.setForeground(new java.awt.Color(255, 51, 51));
        picos205.setText("205 - NÃO CHEGOU");

        picos206.setForeground(new java.awt.Color(255, 51, 51));
        picos206.setText("206 - NÃO CHEGOU");

        picos207.setForeground(new java.awt.Color(255, 51, 51));
        picos207.setText("207 - NÃO CHEGOU");

        picos208.setForeground(new java.awt.Color(255, 51, 51));
        picos208.setText("208 - NÃO CHEGOU");

        picos209.setForeground(new java.awt.Color(255, 51, 51));
        picos209.setText("209 - NÃO CHEGOU");

        picos210.setForeground(new java.awt.Color(255, 51, 51));
        picos210.setText("210 - NÃO CHEGOU");

        picos211.setForeground(new java.awt.Color(255, 51, 51));
        picos211.setText("211 - NÃO CHEGOU");

        picos212.setForeground(new java.awt.Color(255, 51, 51));
        picos212.setText("212 - NÃO CHEGOU");

        picos213.setForeground(new java.awt.Color(255, 51, 51));
        picos213.setText("213 - NÃO CHEGOU");

        picos214.setForeground(new java.awt.Color(255, 51, 51));
        picos214.setText("214 - NÃO CHEGOU");

        picos215.setForeground(new java.awt.Color(255, 51, 51));
        picos215.setText("215 - NÃO CHEGOU");

        picos216.setForeground(new java.awt.Color(255, 51, 51));
        picos216.setText("216 - NÃO CHEGOU");

        picos217.setForeground(new java.awt.Color(255, 51, 51));
        picos217.setText("217 - NÃO CHEGOU");

        picos218.setForeground(new java.awt.Color(255, 51, 51));
        picos218.setText("218 - NÃO CHEGOU");

        picos219.setForeground(new java.awt.Color(255, 51, 51));
        picos219.setText("219 - NÃO CHEGOU");

        picos220.setForeground(new java.awt.Color(255, 51, 51));
        picos220.setText("220 - NÃO CHEGOU");

        picos221.setForeground(new java.awt.Color(255, 51, 51));
        picos221.setText("221 - NÃO CHEGOU");

        picos222.setForeground(new java.awt.Color(255, 51, 51));
        picos222.setText("222 - NÃO CHEGOU");

        picos223.setForeground(new java.awt.Color(255, 51, 51));
        picos223.setText("223 - NÃO CHEGOU");

        picos226.setForeground(new java.awt.Color(255, 51, 51));
        picos226.setText("226 - NÃO CHEGOU");

        picos227.setForeground(new java.awt.Color(255, 51, 51));
        picos227.setText("227 - NÃO CHEGOU");

        picos228.setForeground(new java.awt.Color(255, 51, 51));
        picos228.setText("228 - NÃO CHEGOU");

        picos229.setForeground(new java.awt.Color(255, 51, 51));
        picos229.setText("229 - NÃO CHEGOU");

        picos230.setForeground(new java.awt.Color(255, 51, 51));
        picos230.setText("230 - NÃO CHEGOU");

        picos231.setForeground(new java.awt.Color(255, 51, 51));
        picos231.setText("231 - NÃO CHEGOU");

        picos232.setForeground(new java.awt.Color(255, 51, 51));
        picos232.setText("232 - NÃO CHEGOU");

        picos234.setForeground(new java.awt.Color(255, 51, 51));
        picos234.setText("234 - NÃO CHEGOU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picos209)
                    .addComponent(picos210)
                    .addComponent(picos211)
                    .addComponent(picos212)
                    .addComponent(picos213)
                    .addComponent(picos208)
                    .addComponent(picos202)
                    .addComponent(picos203)
                    .addComponent(picos204)
                    .addComponent(picos205)
                    .addComponent(picos206)
                    .addComponent(picos207)
                    .addComponent(picos201))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picos214)
                    .addComponent(picos220)
                    .addComponent(picos221)
                    .addComponent(picos222)
                    .addComponent(picos223)
                    .addComponent(picos226)
                    .addComponent(picos227)
                    .addComponent(picos228)
                    .addComponent(picos215)
                    .addComponent(picos216)
                    .addComponent(picos217)
                    .addComponent(picos218)
                    .addComponent(picos219))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picos229)
                    .addComponent(picos230)
                    .addComponent(picos231)
                    .addComponent(picos232)
                    .addComponent(picos234))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(picos201)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos202)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos203)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos204)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos205)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos206)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos207)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos208)
                            .addComponent(picos221))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos209)
                            .addComponent(picos222))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos210)
                            .addComponent(picos223))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos211)
                            .addComponent(picos226))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos212)
                            .addComponent(picos227))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos213)
                            .addComponent(picos228)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos214)
                            .addComponent(picos229))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos215)
                            .addComponent(picos230))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos216)
                            .addComponent(picos231))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos217)
                            .addComponent(picos232))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(picos218)
                            .addComponent(picos234))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos219)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picos220)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        srn.addTab("Picos", jPanel3);

        floriano401.setForeground(new java.awt.Color(255, 51, 51));
        floriano401.setText("401 - NÃO CHEGOU");

        floriano402.setForeground(new java.awt.Color(255, 51, 51));
        floriano402.setText("402 - NÃO CHEGOU");

        floriano403.setForeground(new java.awt.Color(255, 51, 51));
        floriano403.setText("403 - NÃO CHEGOU");

        floriano404.setForeground(new java.awt.Color(255, 51, 51));
        floriano404.setText("404 - NÃO CHEGOU");

        floriano405.setForeground(new java.awt.Color(255, 51, 51));
        floriano405.setText("405 - NÃO CHEGOU");

        floriano406.setForeground(new java.awt.Color(255, 51, 51));
        floriano406.setText("406 - NÃO CHEGOU");

        floriano407.setForeground(new java.awt.Color(255, 51, 51));
        floriano407.setText("407 - NÃO CHEGOU");

        floriano408.setForeground(new java.awt.Color(255, 51, 51));
        floriano408.setText("408 - NÃO CHEGOU");

        floriano409.setForeground(new java.awt.Color(255, 51, 51));
        floriano409.setText("409 - NÃO CHEGOU");

        floriano410.setForeground(new java.awt.Color(255, 51, 51));
        floriano410.setText("410 - NÃO CHEGOU");

        floriano411.setForeground(new java.awt.Color(255, 51, 51));
        floriano411.setText("411 - NÃO CHEGOU");

        floriano412.setForeground(new java.awt.Color(255, 51, 51));
        floriano412.setText("412 - NÃO CHEGOU");

        floriano413.setForeground(new java.awt.Color(255, 51, 51));
        floriano413.setText("413 - NÃO CHEGOU");

        floriano414.setForeground(new java.awt.Color(255, 51, 51));
        floriano414.setText("414 - NÃO CHEGOU");

        floriano415.setForeground(new java.awt.Color(255, 51, 51));
        floriano415.setText("415 - NÃO CHEGOU");

        floriano416.setForeground(new java.awt.Color(255, 51, 51));
        floriano416.setText("416 - NÃO CHEGOU");

        floriano417.setForeground(new java.awt.Color(255, 51, 51));
        floriano417.setText("417 - NÃO CHEGOU");

        floriano419.setForeground(new java.awt.Color(255, 51, 51));
        floriano419.setText("419 - NÃO CHEGOU");

        floriano426.setForeground(new java.awt.Color(255, 51, 51));
        floriano426.setText("426 - NÃO CHEGOU");

        floriano427.setForeground(new java.awt.Color(255, 51, 51));
        floriano427.setText("427 - NÃO CHEGOU");

        floriano428.setForeground(new java.awt.Color(255, 51, 51));
        floriano428.setText("428 - NÃO CHEGOU");

        floriano429.setForeground(new java.awt.Color(255, 51, 51));
        floriano429.setText("429 - NÃO CHEGOU");

        floriano430.setForeground(new java.awt.Color(255, 51, 51));
        floriano430.setText("430 - NÃO CHEGOU");

        floriano431.setForeground(new java.awt.Color(255, 51, 51));
        floriano431.setText("431 - NÃO CHEGOU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floriano413)
                    .addComponent(floriano412)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floriano402)
                            .addComponent(floriano403)
                            .addComponent(floriano404)
                            .addComponent(floriano405)
                            .addComponent(floriano401)
                            .addComponent(floriano406)
                            .addComponent(floriano407)
                            .addComponent(floriano409)
                            .addComponent(floriano408)
                            .addComponent(floriano410)
                            .addComponent(floriano411))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floriano431)
                            .addComponent(floriano430)
                            .addComponent(floriano429)
                            .addComponent(floriano428)
                            .addComponent(floriano427)
                            .addComponent(floriano426)
                            .addComponent(floriano415)
                            .addComponent(floriano416)
                            .addComponent(floriano417)
                            .addComponent(floriano419)
                            .addComponent(floriano414))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(floriano401)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano402)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano403)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano404)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano405))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(floriano414)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano415)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano416)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano417)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floriano419)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floriano406)
                            .addComponent(floriano426))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floriano407)
                            .addComponent(floriano427))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floriano408)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floriano409))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(floriano428)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floriano429)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floriano410)
                    .addComponent(floriano430))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floriano411)
                    .addComponent(floriano431))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floriano412)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floriano413)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        srn.addTab("Floriano", jPanel4);

        ativarPicos.setText("Ativar Picos");
        ativarPicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativarPicosActionPerformed(evt);
            }
        });

        ativarPiripiri.setText("Ativar Piripiri");
        ativarPiripiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativarPiripiriActionPerformed(evt);
            }
        });

        ativarFloriano.setText("Ativar Floriano");
        ativarFloriano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativarFlorianoActionPerformed(evt);
            }
        });

        ativarSrn.setText("Ativar SRN");
        ativarSrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativarSrnActionPerformed(evt);
            }
        });

        ativarCaxias.setText("Ativar Caxias");
        ativarCaxias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativarCaxiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ativarFloriano)
                    .addComponent(ativarCaxias)
                    .addComponent(ativarPiripiri)
                    .addComponent(ativarPicos)
                    .addComponent(ativarSrn))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ativarPicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ativarPiripiri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ativarFloriano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ativarSrn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ativarCaxias)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        srn.addTab("Config", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srn)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srn)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piripiriOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piripiriOnTime
        File diretorio = new File("S:\\6433\\VDWIN\\PTPED");
 
        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
                if (pathname.getName().endsWith("301.TXT.GZ") == true) {
                    piripiri301.setText("301 Chegou");
                    piripiri301.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("302.TXT.GZ") == true) {
                    piripiri302.setText("302 Chegou");
                    piripiri302.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("303.TXT.GZ") == true) {
                    piripiri303.setText("303 Chegou");
                    piripiri303.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("304.TXT.GZ") == true) {
                    piripiri304.setText("304 Chegou");
                    piripiri304.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("305.TXT.GZ") == true) {
                    piripiri305.setText("305 Chegou");
                    piripiri305.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("306.TXT.GZ") == true) {
                    piripiri306.setText("306 Chegou");
                    piripiri306.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("307.TXT.GZ") == true) {
                    piripiri307.setText("307 Chegou");
                    piripiri307.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("308.TXT.GZ") == true) {
                    piripiri308.setText("308 Chegou");
                    piripiri308.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("309.TXT.GZ") == true) {
                    piripiri309.setText("309 Chegou");
                    piripiri309.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("310.TXT.GZ") == true) {
                    piripiri310.setText("310 Chegou");
                    piripiri310.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("311.TXT.GZ") == true) {
                    piripiri311.setText("311 Chegou");
                    piripiri311.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("312.TXT.GZ") == true) {
                    piripiri312.setText("312 Chegou");
                    piripiri312.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("313.TXT.GZ") == true) {
                    piripiri313.setText("313 Chegou");
                    piripiri313.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("314.TXT.GZ") == true) {
                    piripiri314.setText("314 Chegou");
                    piripiri314.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("315.TXT.GZ") == true) {
                    piripiri315.setText("315 Chegou");
                    piripiri315.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("316.TXT.GZ") == true) {
                    piripiri316.setText("316 Chegou");
                    piripiri316.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("317.TXT.GZ") == true) {
                    piripiri317.setText("317 Chegou");
                    piripiri317.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("318.TXT.GZ") == true) {
                    piripiri318.setText("318 Chegou");
                    piripiri318.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("319.TXT.GZ") == true) {
                    piripiri319.setText("319 Chegou");
                    piripiri319.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("320.TXT.GZ") == true) {
                    piripiri320.setText("320 Chegou");
                    piripiri320.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("321.TXT.GZ") == true) {
                    piripiri321.setText("321 Chegou");
                    piripiri321.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("322.TXT.GZ") == true) {
                    piripiri322.setText("322 Chegou");
                    piripiri322.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("323.TXT.GZ") == true) {
                    piripiri323.setText("323 Chegou");
                    piripiri323.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("326.TXT.GZ") == true) {
                    piripiri326.setText("326 Chegou");
                    piripiri326.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("327.TXT.GZ") == true) {
                    piripiri327.setText("327 Chegou");
                    piripiri327.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("328.TXT.GZ") == true) {
                    piripiri328.setText("328 Chegou");
                    piripiri328.setForeground(Color.blue);
                }              
                if (pathname.getName().endsWith("329.TXT.GZ") == true) {
                    piripiri329.setText("329 Chegou");
                    piripiri329.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("330.TXT.GZ") == true) {
                    piripiri330.setText("330 Chegou");
                    piripiri330.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("331.TXT.GZ") == true) {
                    piripiri331.setText("331 Chegou");
                    piripiri331.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("332.TXT.GZ") == true) {
                    piripiri332.setText("332 Chegou");
                    piripiri332.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("333.TXT.GZ") == true) {
                    piripiri333.setText("333 Chegou");
                    piripiri333.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("334.TXT.GZ") == true) {
                    piripiri334.setText("334 Chegou");
                    piripiri334.setForeground(Color.blue);
                }                
        return true;
        }      
        });
    }//GEN-LAST:event_piripiriOnTime

    private void florianoOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_florianoOnTime
        File diretorio = new File("S:\\6449\\VDWIN\\PTPED");
 
        File[] listFiles = diretorio.listFiles(new FileFilter() {
            public boolean accept(File pathname) {
                if (pathname.getName().endsWith("401.TXT.GZ") == true) {
                    floriano401.setText("401 Chegou");
                    floriano401.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("402.TXT.GZ") == true) {
                    floriano402.setText("402 Chegou");
                    floriano402.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("403.TXT.GZ") == true) {
                    floriano403.setText("403 Chegou");
                    floriano403.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("404.TXT.GZ") == true) {
                    floriano404.setText("404 Chegou");
                    floriano404.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("405.TXT.GZ") == true) {
                    floriano405.setText("405 Chegou");
                    floriano405.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("406.TXT.GZ") == true) {
                    floriano406.setText("406 Chegou");
                    floriano406.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("407.TXT.GZ") == true) {
                    floriano407.setText("407 Chegou");
                    floriano407.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("408.TXT.GZ") == true) {
                    floriano408.setText("408 Chegou");
                    floriano408.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("409.TXT.GZ") == true) {
                    floriano409.setText("409 Chegou");
                    floriano409.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("410.TXT.GZ") == true) {
                    floriano410.setText("410 Chegou");
                    floriano410.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("411.TXT.GZ") == true) {
                    floriano411.setText("411 Chegou");
                    floriano411.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("412.TXT.GZ") == true) {
                    floriano412.setText("412 Chegou");
                    floriano412.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("413.TXT.GZ") == true) {
                    floriano413.setText("413 Chegou");
                    floriano413.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("414.TXT.GZ") == true) {
                    floriano414.setText("414 Chegou");
                    floriano414.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("415.TXT.GZ") == true) {
                    floriano415.setText("415 Chegou");
                    floriano415.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("416.TXT.GZ") == true) {
                    floriano416.setText("416 Chegou");
                    floriano416.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("417.TXT.GZ") == true) {
                    floriano417.setText("417 Chegou");
                    floriano417.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("419.TXT.GZ") == true) {
                    floriano419.setText("419 Chegou");
                    floriano419.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("426.TXT.GZ") == true) {
                    floriano426.setText("426 Chegou");
                    floriano426.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("427.TXT.GZ") == true) {
                    floriano427.setText("427 Chegou");
                    floriano427.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("428.TXT.GZ") == true) {
                    floriano428.setText("428 Chegou");
                    floriano428.setForeground(Color.blue);
                }              
                if (pathname.getName().endsWith("429.TXT.GZ") == true) {
                    floriano429.setText("429 Chegou");
                    floriano429.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("430.TXT.GZ") == true) {
                    floriano430.setText("430 Chegou");
                    floriano430.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("431.TXT.GZ") == true) {
                    floriano431.setText("431 Chegou");
                    floriano431.setForeground(Color.blue);
                }
        return true;
        }      
        });
    }//GEN-LAST:event_florianoOnTime

    private void picosOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picosOnTime
        File diretorio = new File("S:\\6429\\VDWIN\\PTPED");

        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
                if (pathname.getName().endsWith("201.TXT.GZ") == true) {
                    picos201.setText("201 Chegou");
                    picos201.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("202.TXT.GZ") == true) {
                    picos202.setText("202 Chegou");
                    picos202.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("203.TXT.GZ") == true) {
                    picos203.setText("203 Chegou");
                    picos203.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("204.TXT.GZ") == true) {
                    picos204.setText("204 Chegou");
                    picos204.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("205.TXT.GZ") == true) {
                    picos205.setText("205 Chegou");
                    picos205.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("206.TXT.GZ") == true) {
                    picos206.setText("206 Chegou");
                    picos206.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("207.TXT.GZ") == true) {
                    picos207.setText("207 Chegou");
                    picos207.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("208.TXT.GZ") == true) {
                    picos208.setText("208 Chegou");
                    picos208.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("209.TXT.GZ") == true) {
                    picos209.setText("209 Chegou");
                    picos209.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("210.TXT.GZ") == true) {
                    picos210.setText("210 Chegou");
                    picos210.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("211.TXT.GZ") == true) {
                    picos211.setText("211 Chegou");
                    picos211.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("212.TXT.GZ") == true) {
                    picos212.setText("212 Chegou");
                    picos212.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("213.TXT.GZ") == true) {
                    picos213.setText("213 Chegou");
                    picos213.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("214.TXT.GZ") == true) {
                    picos214.setText("214 Chegou");
                    picos214.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("215.TXT.GZ") == true) {
                    picos215.setText("215 Chegou");
                    picos215.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("216.TXT.GZ") == true) {
                    picos216.setText("216 Chegou");
                    picos216.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("217.TXT.GZ") == true) {
                    picos217.setText("217 Chegou");
                    picos217.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("218.TXT.GZ") == true) {
                    picos218.setText("218 Chegou");
                    picos218.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("219.TXT.GZ") == true) {
                    picos219.setText("219 Chegou");
                    picos219.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("220.TXT.GZ") == true) {
                    picos220.setText("220 Chegou");
                    picos220.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("221.TXT.GZ") == true) {
                    picos221.setText("221 Chegou");
                    picos221.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("222.TXT.GZ") == true) {
                    picos222.setText("222 Chegou");
                    picos222.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("223.TXT.GZ") == true) {
                    picos223.setText("223 Chegou");
                    picos223.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("226.TXT.GZ") == true) {
                    picos226.setText("226 Chegou");
                    picos226.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("227.TXT.GZ") == true) {
                    picos227.setText("227 Chegou");
                    picos227.setForeground(Color.blue);
                }                
                if (pathname.getName().endsWith("228.TXT.GZ") == true) {
                    picos228.setText("228 Chegou");
                    picos228.setForeground(Color.blue);
                }              
                if (pathname.getName().endsWith("229.TXT.GZ") == true) {
                    picos229.setText("229 Chegou");
                    picos229.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("230.TXT.GZ") == true) {
                    picos230.setText("230 Chegou");
                    picos230.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("231.TXT.GZ") == true) {
                    picos231.setText("231 Chegou");
                    picos231.setForeground(Color.blue);
                }               
                if (pathname.getName().endsWith("232.TXT.GZ") == true) {
                    picos232.setText("232 Chegou");
                    picos232.setForeground(Color.blue);
                }                          
                if (pathname.getName().endsWith("234.TXT.GZ") == true) {
                    picos234.setText("234 Chegou");
                    picos234.setForeground(Color.blue);
                }                
        return true;
        }      
        });
    }//GEN-LAST:event_picosOnTime

    private void caxiasOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caxiasOnTime
        File diretorio = new File("S:\\6648\\VDWIN\\PTPED");
	
        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
            if (pathname.getName().endsWith("101.TXT.GZ") == true) {
                caxias101.setText("101 Chegou");
                caxias101.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("102.TXT.GZ") == true) {
                caxias102.setText("102 Chegou");
                caxias102.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("101.TXT.GZ") == true) {
                caxias103.setText("101 Chegou");
                caxias103.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("104.TXT.GZ") == true) {
                caxias104.setText("104 Chegou");
                caxias104.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("105.TXT.GZ") == true) {
                caxias105.setText("105 Chegou");
                caxias105.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("106.TXT.GZ") == true) {
                caxias106.setText("106 Chegou");
                caxias106.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("107.TXT.GZ") == true) {
                caxias107.setText("107 Chegou");
                caxias107.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("108.TXT.GZ") == true) {
                caxias108.setText("108 Chegou");
                caxias108.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("109.TXT.GZ") == true) {
                caxias109.setText("109 Chegou");
                caxias109.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("110.TXT.GZ") == true) {
                caxias110.setText("110 Chegou");
                caxias110.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("111.TXT.GZ") == true) {
                caxias111.setText("111 Chegou");
                caxias111.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("112.TXT.GZ") == true) {
                caxias112.setText("112 Chegou");
                caxias112.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("113.TXT.GZ") == true) {
                caxias113.setText("113 Chegou");
                caxias113.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("114.TXT.GZ") == true) {
                caxias114.setText("114 Chegou");
                caxias114.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("116.TXT.GZ") == true) {
                caxias116.setText("116 Chegou");
                caxias116.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("121.TXT.GZ") == true) {
                caxias121.setText("121 Chegou");
                caxias121.setForeground(Color.blue);
                }
            if (pathname.getName().endsWith("122.TXT.GZ") == true) {
                caxias122.setText("122 Chegou");
                caxias122.setForeground(Color.blue);
                }
             if (pathname.getName().endsWith("123.TXT.GZ") == true) {
                caxias123.setText("123 Chegou");
                caxias123.setForeground(Color.blue);
                }

               return true;
        }      
        });
    }//GEN-LAST:event_caxiasOnTime

    private void sraimundoOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sraimundoOnTime
        File diretorio = new File("S:\\6456\\VDWIN\\PTPED");
	
        File[] listFiles = diretorio.listFiles(new FileFilter() {
	public boolean accept(File pathname) {
                if (pathname.getName().endsWith("501.TXT.GZ") == true) {
                    srn501.setText("501 Chegou");
                    srn501.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("502.TXT.GZ") == true) {
                    srn502.setText("502 Chegou");
                    srn502.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("503.TXT.GZ") == true) {
                    srn503.setText("503 Chegou");
                    srn503.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("504.TXT.GZ") == true) {
                    srn504.setText("504 Chegou");
                    srn504.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("505.TXT.GZ") == true) {
                    srn505.setText("505 Chegou");
                    srn505.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("506.TXT.GZ") == true) {
                    srn506.setText("506 Chegou");
                    srn506.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("507.TXT.GZ") == true) {
                    srn507.setText("507 Chegou");
                    srn507.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("511.TXT.GZ") == true) {
                    srn511.setText("511 Chegou");
                    srn511.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("512.TXT.GZ") == true) {
                    srn512.setText("512 Chegou");
                    srn512.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("513.TXT.GZ") == true) {
                    srn513.setText("513 Chegou");
                    srn513.setForeground(Color.blue);
                }
                if (pathname.getName().endsWith("514.TXT.GZ") == true) {
                    srn514.setText("514 Chegou");
                    srn514.setForeground(Color.blue);
                }
        return true;
        }      
        });
    }//GEN-LAST:event_sraimundoOnTime

    private void ativarPicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativarPicosActionPerformed
        if(ativarPicos.isSelected()){
          picos.start();  
        }else{
          picos.stop();
        }
        
    }//GEN-LAST:event_ativarPicosActionPerformed

    private void ativarPiripiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativarPiripiriActionPerformed
        if(ativarPiripiri.isSelected()){
            piripiri.start();
        }else{
            piripiri.stop();
        }
    }//GEN-LAST:event_ativarPiripiriActionPerformed

    private void ativarFlorianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativarFlorianoActionPerformed
        if(ativarFloriano.isSelected()){
            floriano.start();
        }else{
            floriano.stop();
        }
    }//GEN-LAST:event_ativarFlorianoActionPerformed

    private void ativarSrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativarSrnActionPerformed
        if(ativarSrn.isSelected()){
            sraimundo.start();
        }else{
            sraimundo.stop();
        }
    }//GEN-LAST:event_ativarSrnActionPerformed

    private void ativarCaxiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativarCaxiasActionPerformed
        if(ativarCaxias.isSelected()){
            caxias.start();
        }else{
            caxias.stop();
        }
    }//GEN-LAST:event_ativarCaxiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativarCaxias;
    private javax.swing.JCheckBox ativarFloriano;
    private javax.swing.JCheckBox ativarPicos;
    private javax.swing.JCheckBox ativarPiripiri;
    private javax.swing.JCheckBox ativarSrn;
    private org.netbeans.examples.lib.timerbean.Timer caxias;
    private javax.swing.JLabel caxias101;
    private javax.swing.JLabel caxias102;
    private javax.swing.JLabel caxias103;
    private javax.swing.JLabel caxias104;
    private javax.swing.JLabel caxias105;
    private javax.swing.JLabel caxias106;
    private javax.swing.JLabel caxias107;
    private javax.swing.JLabel caxias108;
    private javax.swing.JLabel caxias109;
    private javax.swing.JLabel caxias110;
    private javax.swing.JLabel caxias111;
    private javax.swing.JLabel caxias112;
    private javax.swing.JLabel caxias113;
    private javax.swing.JLabel caxias114;
    private javax.swing.JLabel caxias116;
    private javax.swing.JLabel caxias121;
    private javax.swing.JLabel caxias122;
    private javax.swing.JLabel caxias123;
    private org.netbeans.examples.lib.timerbean.Timer floriano;
    private javax.swing.JLabel floriano401;
    private javax.swing.JLabel floriano402;
    private javax.swing.JLabel floriano403;
    private javax.swing.JLabel floriano404;
    private javax.swing.JLabel floriano405;
    private javax.swing.JLabel floriano406;
    private javax.swing.JLabel floriano407;
    private javax.swing.JLabel floriano408;
    private javax.swing.JLabel floriano409;
    private javax.swing.JLabel floriano410;
    private javax.swing.JLabel floriano411;
    private javax.swing.JLabel floriano412;
    private javax.swing.JLabel floriano413;
    private javax.swing.JLabel floriano414;
    private javax.swing.JLabel floriano415;
    private javax.swing.JLabel floriano416;
    private javax.swing.JLabel floriano417;
    private javax.swing.JLabel floriano419;
    private javax.swing.JLabel floriano426;
    private javax.swing.JLabel floriano427;
    private javax.swing.JLabel floriano428;
    private javax.swing.JLabel floriano429;
    private javax.swing.JLabel floriano430;
    private javax.swing.JLabel floriano431;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private org.netbeans.examples.lib.timerbean.Timer picos;
    private javax.swing.JLabel picos201;
    private javax.swing.JLabel picos202;
    private javax.swing.JLabel picos203;
    private javax.swing.JLabel picos204;
    private javax.swing.JLabel picos205;
    private javax.swing.JLabel picos206;
    private javax.swing.JLabel picos207;
    private javax.swing.JLabel picos208;
    private javax.swing.JLabel picos209;
    private javax.swing.JLabel picos210;
    private javax.swing.JLabel picos211;
    private javax.swing.JLabel picos212;
    private javax.swing.JLabel picos213;
    private javax.swing.JLabel picos214;
    private javax.swing.JLabel picos215;
    private javax.swing.JLabel picos216;
    private javax.swing.JLabel picos217;
    private javax.swing.JLabel picos218;
    private javax.swing.JLabel picos219;
    private javax.swing.JLabel picos220;
    private javax.swing.JLabel picos221;
    private javax.swing.JLabel picos222;
    private javax.swing.JLabel picos223;
    private javax.swing.JLabel picos226;
    private javax.swing.JLabel picos227;
    private javax.swing.JLabel picos228;
    private javax.swing.JLabel picos229;
    private javax.swing.JLabel picos230;
    private javax.swing.JLabel picos231;
    private javax.swing.JLabel picos232;
    private javax.swing.JLabel picos234;
    private org.netbeans.examples.lib.timerbean.Timer piripiri;
    private javax.swing.JLabel piripiri301;
    private javax.swing.JLabel piripiri302;
    private javax.swing.JLabel piripiri303;
    private javax.swing.JLabel piripiri304;
    private javax.swing.JLabel piripiri305;
    private javax.swing.JLabel piripiri306;
    private javax.swing.JLabel piripiri307;
    private javax.swing.JLabel piripiri308;
    private javax.swing.JLabel piripiri309;
    private javax.swing.JLabel piripiri310;
    private javax.swing.JLabel piripiri311;
    private javax.swing.JLabel piripiri312;
    private javax.swing.JLabel piripiri313;
    private javax.swing.JLabel piripiri314;
    private javax.swing.JLabel piripiri315;
    private javax.swing.JLabel piripiri316;
    private javax.swing.JLabel piripiri317;
    private javax.swing.JLabel piripiri318;
    private javax.swing.JLabel piripiri319;
    private javax.swing.JLabel piripiri320;
    private javax.swing.JLabel piripiri321;
    private javax.swing.JLabel piripiri322;
    private javax.swing.JLabel piripiri323;
    private javax.swing.JLabel piripiri326;
    private javax.swing.JLabel piripiri327;
    private javax.swing.JLabel piripiri328;
    private javax.swing.JLabel piripiri329;
    private javax.swing.JLabel piripiri330;
    private javax.swing.JLabel piripiri331;
    private javax.swing.JLabel piripiri332;
    private javax.swing.JLabel piripiri333;
    private javax.swing.JLabel piripiri334;
    private javax.swing.JPanel saoraimundo;
    private javax.swing.JPanel saoraimundo1;
    private org.netbeans.examples.lib.timerbean.Timer sraimundo;
    private javax.swing.JTabbedPane srn;
    private javax.swing.JLabel srn501;
    private javax.swing.JLabel srn502;
    private javax.swing.JLabel srn503;
    private javax.swing.JLabel srn504;
    private javax.swing.JLabel srn505;
    private javax.swing.JLabel srn506;
    private javax.swing.JLabel srn507;
    private javax.swing.JLabel srn511;
    private javax.swing.JLabel srn512;
    private javax.swing.JLabel srn513;
    private javax.swing.JLabel srn514;
    // End of variables declaration//GEN-END:variables
}
